import "../src/load-env.js";
import { readFile, writeFile, mkdir } from "node:fs/promises";
import { resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { randomUUID } from "node:crypto";
import { Hono } from "hono";
import { serve } from "@hono/node-server";
import { Queue } from "bullmq";
import { AgentService } from "../src/services/agent-service.js";
import { loadLlmConfig } from "../src/config.js";
import { createConversationRoutes } from "../src/routes/conversations.js";
import { createAuthMiddleware } from "../src/auth/middleware.js";
import { KnowledgeRepository } from "../src/knowledge/repository.js";
import { KnowledgeJobs } from "../src/knowledge/ingestion/jobs.js";
import { indexArtifact } from "../src/knowledge/ingestion/indexer.js";
import { createUserEmbedder } from "../src/knowledge/ingestion/runtime.js";
import { indexProfile } from "../src/knowledge/ingestion/profile.js";
import { textBlocks } from "../src/knowledge/ingestion/text.js";
import { PARSER_VERSION } from "../src/knowledge/ingestion/version.js";
import { getRedis } from "../src/jobs/redis.js";
import { knowledgeRedisOptions } from "../src/knowledge/ingestion/config.js";
if (!process.argv.includes("--live") || !process.argv.includes("--latest-user")) throw new Error("Requires --live --latest-user");
if (!["localhost", "127.0.0.1", "::1"].includes(process.env.PG_HOST ?? "localhost")) throw new Error("Local database only");
process.env.DEBUG_LLM = "0";
const root = fileURLToPath(new URL("../../../", import.meta.url));
const config = JSON.parse(await readFile(resolve(root, "config/default.json"), "utf8"));
const service = new AgentService({ knowledge: { source: "local" }, llm: await loadLlmConfig(root), models: config.models, modelCatalog: config.modelCatalog, agent: { ...config.agent, maxIterations: 3 }, skillsDir: resolve(root, "skills"), mcpConfigPath: resolve(root,"config/no-test-mcp.json"), debug: false, managedKeysEnabled: process.env.NEW_API_MANAGED_KEYS !== "0", db: { host: process.env.PG_HOST, port: Number(process.env.PG_PORT ?? 5432), user: process.env.PG_USER, password: process.env.PG_PASSWORD, database: process.env.PG_DATABASE } });
let server: ReturnType<typeof serve> | undefined; let owner: string | undefined; let collection: string | undefined; let item: string | undefined; let token: string | undefined;
const conversation = randomUUID(); const queueName = `rag-chat-${conversation}`;
try {
  await service.init();
  owner = (await service.db.pool.query("SELECT user_id FROM sessions ORDER BY last_seen_at DESC LIMIT 1")).rows[0]?.user_id;
  if (!owner) throw new Error("No authorized account");
  const key = await service.db.getUserApiKey(owner, service.managedKeysEnabled);
  if (!key) throw new Error("User credential unavailable");
  const catalog = await service.getUserModelCatalog(owner, key);
  const model = catalog?.llm.find((m) => m.id === process.env.OPENAI_MODEL)?.id ?? catalog?.llm.find((m) => !/embedding|rerank|image|video/i.test(m.id))?.id;
  if (!model) throw new Error("No chat model");
  const repo = new KnowledgeRepository(service.db.pool, queueName); const jobs = new KnowledgeJobs(service.db.pool);
  collection = (await repo.createCollection(owner, { name: "S3/S4 真实聊天验收", description: "synthetic, removed after check" }, randomUUID())).id;
  const nonce = `S4-${randomUUID().slice(0,8)}`; const text = `测试设备的离线启用码为 ${nonce}。离线使用前需要先完成资料下载。`;
  const created = await repo.createItem(owner, { sourceType: "note", title: "离线设备说明", content: text, description: "", tags: [], collectionIds: [collection] }, randomUUID()); item = created.id;
  const profile = indexProfile(process.env.OPENAI_BASE_URL!);
  await indexArtifact(jobs, (await jobs.claim(created.taskId!, queueName))!, profile, { blocks: textBlocks(text), diagnostics: [], parserVersion: PARSER_VERSION }, createUserEmbedder(service.db, profile, owner, created.taskId));
  await service.db.createConversation(conversation,"S4 live chat check",model,"openai","general",owner);
  token = await service.sessions.createSession(owner);
  const app = new Hono(); app.use("/api/*", createAuthMiddleware(service.sessions)); app.route("/api/conversations",createConversationRoutes(service));
  server = serve({ fetch: app.fetch, port: 0, hostname: "127.0.0.1" }); await new Promise<void>((r) => server!.listening ? r() : server!.once("listening",r));
  const address = server.address(); if (!address || typeof address === "string") throw new Error("No HTTP address");
  const base = `http://127.0.0.1:${address.port}/api/conversations/${conversation}`;
  const headers = { Authorization: `Bearer ${token}`, "Content-Type":"application/json" };
  const selected = await fetch(`${base}/knowledge-bases`, { method:"PUT",headers,body:JSON.stringify({ knowledgeBaseIds:[collection] }) }); if (!selected.ok) throw new Error(`Selection HTTP ${selected.status}`); await selected.arrayBuffer();
  const response = await fetch(`${base}/messages`, { method:"POST",headers,body:JSON.stringify({ content:"只根据选定知识库回答：测试设备离线启用码是什么，离线前要做什么？引用资料名称，不调用额外工具。",modelId:model }),signal:AbortSignal.timeout(180000) });
  if (!response.ok) throw new Error(`Chat HTTP ${response.status}`);
  const wire = await response.text();
  const events = wire.split("\n").filter((line) => line.startsWith("data:")).map((line) => JSON.parse(line.slice(5)));
  if (events.some((e) => e.type === "error")) throw new Error("Chat emitted error (payload omitted)");
  const evidence = events.find((e) => e.type === "knowledge_sources")?.sources;
  const answer = events.filter((e) => e.type === "text").map((e) => e.content).join("");
  if (!answer.includes(nonce) || !evidence?.some((e: { itemId:string; revisionId:string }) => e.itemId === item && e.revisionId === created.revisionId) || !events.some((e) => e.type === "stream_end")) throw new Error("Answer or SSE evidence mismatch");
  const messages = await service.db.getMessages(conversation);
  if (!messages.some((m) => m.role === "assistant" && m.content.includes(nonce) && Array.isArray(m.metadata.knowledgeSources))) throw new Error("Persisted answer/source mismatch");
  await mkdir(resolve(root,"tests/eval/results"),{recursive:true});
  await writeFile(resolve(root,"tests/eval/results/chat.json"),JSON.stringify({ finished:new Date().toISOString(), model, source:"local", realEmbedding:true, realLLM:true, HTTPBearerSession:true, SSEStreamEnd:true, answerContainsSyntheticNonce:true, versionedCitationPersisted:true, noReplyOrCredentialsInReport:true },null,2));
  console.log(JSON.stringify({ chatPassed:true,model,realModels:true,report:"tests/eval/results/chat.json" }));
} finally {
  if (server) await new Promise<void>((r) => server!.close(() => r()));
  if (token) await service.sessions.revoke(token);
  if (owner) {
    // Remove only background tasks belonging to this synthetic conversation/ingestion.
    const tasks = (await service.db.pool.query("SELECT id FROM tasks WHERE user_id=$1::text AND (input->>'conversationId'=$2 OR id IN(SELECT task_id FROM rag_ingestion_runs WHERE owner_id=$1::uuid AND item_id=$3::uuid))",[owner,conversation,item??null])).rows;
    const q = new Queue("lot-tasks",{connection:{...knowledgeRedisOptions(),maxRetriesPerRequest:1}});
    for (const task of tasks) { const job = await q.getJob(task.id); if (job) await job.remove(); await service.db.pool.query("DELETE FROM tasks WHERE id=$1",[task.id]); } await q.close();
    if (item) await service.db.pool.query("DELETE FROM rag_items WHERE owner_id=$1 AND id=$2",[owner,item]);
    if (collection) await service.db.pool.query("DELETE FROM rag_collections WHERE owner_id=$1 AND id=$2",[owner,collection]);
    await service.db.pool.query("DELETE FROM conversations WHERE id=$1 AND user_id=$2",[conversation,owner]);
    await getRedis().del(`mem:session:${conversation}`);
  }
  await service.shutdown(); await service.redis?.quit().catch(() => {}); await getRedis().quit();
}
